using System.Collections;
using UnityEngine;

public class musicOff : MonoBehaviour {

    public GameObject musicon;
    public GameObject musicoff;

    public AudioClip click;

    private void OnMouseDown()
    {
        transform.localScale += new Vector3(0.1f, 0.1f, 0.1f);

        musicOn.music = 1;

        PlayerPrefs.SetInt("music", musicOn.music);

        if (PlayerPrefs.GetInt("sound") == 1)
        {
            StartCoroutine(Click());
        }
    }

    private void OnMouseUp()
    {
        transform.localScale -= new Vector3(0.1f, 0.1f, 0.1f);

        musicon.SetActive(true);
        musicoff.SetActive(false);
    }

    IEnumerator Click()
    {
        AudioSource.PlayClipAtPoint(click, transform.position);
        yield return new WaitForSeconds(0.5f);
    }
}
